version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Stockholm'  # Change to your timezone
      WEBPASSWORD: '${PIHOLE_PASSWORD}'  # Change this!
      # Uncomment the next line if you want to use conditional forwarding
      # CONDITIONAL_FORWARDING: true
      # CONDITIONAL_FORWARDING_IP: 192.168.1.1  # Your router's IP
      # CONDITIONAL_FORWARDING_DOMAIN: local
      # CONDITIONAL_FORWARDING_REVERSE: 1.168.192.in-addr.arpa
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
